baseURL = 'http://mdonovan.dev/'
languageCode = 'en-us'
title = 'Michael Donovan'
theme = "hello-friend-ng"

enableRobotsTXT = true

[author]
  name = "Michael Donovan"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
#  description = ""
#  keywords = "homepage, blog"
  images = [""]

#[taxonomies]
#    category = "blog"
#    tag      = "tags"
#    series   = "series"
[[params.social]]
  name = "email"
  url = "mailto:michael@mdonovan.dev"
[[params.social]]
  name = "github"
  url = "https://github.com/michaeldonovan"
[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/michaelbdonovan"

[params.footer]
  trademark = true 
#  copyright = true
#  bottomText = [
#    "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
#  ]
[languages]
  [languages.en]
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark = " "
      logoCursorDisabled = true
      enable = false
      logoText = " "
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
    url        = "/posts"
